language: bash

services:
- docker

script:
- "env"
- "./ci/docker_build.sh"

deploy:
- provider: script
  skip_cleanup: true
  script: "./ci/publish_latest.sh"
  on:
    tags: false
    branch: master
- provider: script
  skip_cleanup: true
  script: "./ci/publish_tag.sh"
  on:
    tags: true

env:
  global:
  - 'JFROG_DEPLOY_USER=test-user'
  - 'JFROG_DEPLOY_KEY=test-pass'
  - 'QUAYIO_USER=test-user'
  - 'QUAYIO_PASS=test-pass'
  - 'DOCKERHUB_USER=test-user'
  - 'DOCKERHUB_PASS=test-pass'
